[package]
name = "wifi"
version = "0.3.0"
edition = "2021"
authors = ["Bryan Hyland <bryan.hyland32@gmail.com>"]
description = "GUI wrapper for Linux NetworkManager. Manages WiFi, Ethernet, and VPN connections with COSMIC DE integration."

[dependencies]
cmd_lib = { path = "../cmd_lib", features = ["async"] }
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
tracing = "0.1"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = [
    "tokio",
    "winit",
    "wayland",
    "wgpu",
]
