[package]
name = "wifi_cli"
version = "0.1.0"
edition = "2021"
authors = ["Bryan Hyland <bryan.hyland32@gmail.com>"]
description = "Simple wrapper for Linux Network Manager functionality."

[dependencies]
cmd_lib = { path = "../cmd_lib" }
clap = { version = "4.5.15", features = ["derive"] }

