[package]
name = "wifi_cli"
version = "0.3.0"
edition = "2021"
authors = ["Bryan Hyland <bryan.hyland32@gmail.com>"]
description = "CLI wrapper for Linux Network Manager to manage WiFi, Ethernet, and VPN connections."

[dependencies]
cmd_lib = { path = "../cmd_lib" }
clap = { version = "4.5.15", features = ["derive"] }
rpassword = "7.3.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde_json = "1"
